<a href="https://colab.research.google.com/github/alihojatnia/Efficient_Python_tricks_and_tools_for_data_scientists/blob/master/name_to_smiles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%%capture
!pip install pubchempy

In [ ]:
%%capture
import numpy as np
import pandas as pd

try:
    import rdkit
except ModuleNotFoundError:
    !pip install rdkit

    # !pip install kora
    # import kora.install.rdkit
    import rdkit

In [ ]:
from rdkit.Chem import MACCSkeys
from rdkit import DataStructs
from rdkit import Chem
from rdkit import Chem
from rdkit.Chem.Draw import IPythonConsole
from rdkit.Chem import rdDepictor
from rdkit.Chem.Draw import rdMolDraw2D
from IPython.display import SVG

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import time

In [ ]:
import pubchempy as pcp

,covid_index,Drug name,Clinical phase,fda,amu_index
0,1,Argatroban,4,0,870
1,2,Artemisinin,2,0,892
2,3,Artesunate,2,0,381
3,6,azathioprine,3,0,369
4,7,Azithromycin (supporting agent),4,1,8
...,...,...,...,...,...
192,608,Inosine,NaN,0,1343
193,621,acetaminophen,NaN,0,754
194,622,Acetylsalicylic acid,Phase 3,0,93
195,626,Angiotensin converting enzyme 2 (A,Phase 2,0,392
196,627,Antithrombotic,Phase 2 Phase 3,0,117

In [ ]:
pcp.get_cids(df['Drug name'][1],'name')

[68827]

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/drug_fda_phase.csv')
sm = []
for i in range(len(df)):
  try:
    r = pcp.get_cids(df['Drug name'][i],'name')
    c = pcp.Compound.from_cid(r[0])
    z = c.isomeric_smiles
    print(i)
    sm.append(z)
    time.sleep(0.05)
  except:
    sm.append('Nan')
    print('*********** Nan *********')

0
1
2
3
*********** Nan *********
5
6
7
8
9
10
*********** Nan *********
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
*********** Nan *********
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
*********** Nan *********
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
*********** Nan *********
96
97
98
99
100
101
102
103
104
105
106
107
108
*********** Nan *********
110
111
112
113
*********** Nan *********
115
116
117
118
119
120
121
122
123
124
125
126
127
*********** Nan *********
129
130
131
132
133
134
135
*********** Nan *********
137
138
139
140
141
142
143
*********** Nan *********
145
146
147
148
149
150
*********** Nan *********
152
153
154
155
*********** Nan *********
*********** Nan *********
158
159
160
161
162
*********** Nan *********
164
165
*********** Nan *********
167
168
169
170
171
172
173
174
175
176
177
*********** Nan *********
179
180
181
182
183
184
185
*********** Nan *********
187
188
189
190
191
192
193
194
*********** Nan *********
*********** Nan *********

In [ ]:
df['smiles'] = sm
df

,covid_index,Drug name,Clinical phase,fda,amu_index,smiles
0,1,Argatroban,4,0,870,C[C@@H]1CCN([C@H](C1)C(=O)O)C(=O)[C@H](CCCN=C(...
1,2,Artemisinin,2,0,892,C[C@@H]1CC[C@H]2[C@H](C(=O)O[C@H]3[C@@]24[C@H]...
2,3,Artesunate,2,0,381,C[C@@H]1CC[C@H]2[C@H]([C@@H](O[C@H]3[C@@]24[C@...
3,6,azathioprine,3,0,369,CN1C=NC(=C1SC2=NC=NC3=C2NC=N3)[N+](=O)[O-]
4,7,Azithromycin (supporting agent),4,1,8,Nan
...,...,...,...,...,...,...
192,608,Inosine,NaN,0,1343,C1=NC2=C(C(=O)N1)N=CN2[C@H]3[C@@H]([C@@H]([C@H...
193,621,acetaminophen,NaN,0,754,CC(=O)NC1=CC=C(C=C1)O
194,622,Acetylsalicylic acid,Phase 3,0,93,CC(=O)OC1=CC=CC=C1C(=O)O
195,626,Angiotensin converting enzyme 2 (A,Phase 2,0,392,Nan
196,627,Antithrombotic,Phase 2 Phase 3,0,117,Nan